apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
agents: 1
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
registries:
  config: |
    mirrors:
      "k3d-registry.local:5000":
        endpoint:
          - http://k3d-registry.local:5000
