apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: hitcounter
build:
  artifacts:
    - image: registry.local:5000/hitcounter
      docker:
        dockerfile: Dockerfile
test:
  - context: .
    image: hitcounter
    custom:
      - command: DATABASE_URI=redis://localhost:6379/0 green
manifests:
  rawYaml:
    - deploy/**
  # kustomize:
  #   paths:
  #     - "kubernetes/dev"
