version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: devops
    container_name: app
    # init: true
    # privileged: true
    # ports:
    #   - 8000:8000
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      PORT: 8080
      DATABASE_URI: "redis://redis:6379/0"
    networks:
      - dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - dev

volumes:
  redis:
    
networks:
  dev: null
