apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

namespace: prod

# namePrefix: prod-
commonLabels:
  env: prod

resources:
  - namespace.yaml

patches:
  - replica-count.yaml
  - node-port.yaml

images:
  - name: de.icr.io/nyu-devops/hitcounter
    newTag: 1.0.1
