name: CI Build
on:
  push:
    branches:
      - master
    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.devcontainers/**'

  pull_request:
    branches:
      - master
    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.devcontainers/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services    
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # check for omplexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint on the service and tests folders only
          pylint service tests --max-line-length=127

      - name: Run unit tests with green
        run: green
        env:
          DATABASE_URI: "redis://redis:6379/0"
          RETRY_COUNT: 2

      - name: Upload code coverage
        uses: codecov/codecov-action@v3.1.4
